# Generated by Django 4.1.2 on 2022-10-13 15:14

import computed_property.fields
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100, null=True)),
                ('date', computed_property.fields.ComputedDateField(compute_from='datee', editable=False, null=True)),
                ('time', computed_property.fields.ComputedTimeField(compute_from='timee', editable=False, null=True)),
                ('checkin', models.CharField(default=0, max_length=3, null=True)),
                ('checkout', models.CharField(default=0, max_length=3, null=True)),
                ('checkFI', models.CharField(choices=[('IN', 'CheckIN'), ('OU', 'CheckOUT')], default='', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('IPAddress', computed_property.fields.ComputedCharField(compute_from='ip', editable=False, max_length=192, null=True)),
                ('Hostnametest', computed_property.fields.ComputedCharField(compute_from='host', editable=False, max_length=192, null=True)),
                ('user_name', computed_property.fields.ComputedCharField(compute_from='user', editable=False, max_length=192, null=True, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Checks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100, null=True)),
                ('date', computed_property.fields.ComputedDateField(compute_from='datee', editable=False, null=True)),
                ('time', computed_property.fields.ComputedTimeField(compute_from='timee', editable=False, null=True)),
                ('Check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Check_attendances', to='API.attendance')),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
